### PR TITLE
Update all-updates

### PR DESCRIPTION
**Pull request by goafabric**
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [io.quarkus:quarkus-bom](https://redirect.github.com/quarkusio/quarkus) | `3.26.3` -> `3.28.1` | [age](https://docs.renovatebot.com/merge-confidence/) | [confidence](https://docs.renovatebot.com/merge-confidence/) |
| [org.assertj:assertj-core](https://assertj.github.io/doc/#assertj-core) ([source](https://redirect.github.com/assertj/assertj)) | `3.27.4` -> `3.27.6` | [age](https://docs.renovatebot.com/merge-confidence/) | [confidence](https://docs.renovatebot.com/merge-confidence/) |
| io.quarkus | `3.26.3` -> `3.28.1` | [age](https://docs.renovatebot.com/merge-confidence/) | [confidence](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>quarkusio/quarkus (io.quarkus:quarkus-bom)</summary>

### [`v3.28.1`](https://redirect.github.com/quarkusio/quarkus/releases/tag/3.28.1)

[Compare Source](https://redirect.github.com/quarkusio/quarkus/compare/3.28.0...3.28.1)

##### Complete changelog

- [#&#8203;32361](https://redirect.github.com/quarkusio/quarkus/issues/32361) - Error when using withTransaction in RedisDataSource in clustered mode
- [#&#8203;49405](https://redirect.github.com/quarkusio/quarkus/issues/49405) - \[quarkus-kubernetes-client]: DevServicesKubernetesProcessor always shuts down cluster because of broken equals method
- [#&#8203;49531](https://redirect.github.com/quarkusio/quarkus/issues/49531) - `BlockingRedisDataSourceImpl` doesn't call DISCARD if consumer function throws an exception
- [#&#8203;49593](https://redirect.github.com/quarkusio/quarkus/issues/49593) - After Hibernate ORM 7.1.0.CR2 bump, the `jakarta.data.repository.BasicRepository#saveAll` method fails if Hibernate Validator is present and entity has `OneToMany` relation
- [#&#8203;49719](https://redirect.github.com/quarkusio/quarkus/issues/49719) - Redis: if enqueued operation returns an error don't discard them
- [#&#8203;49780](https://redirect.github.com/quarkusio/quarkus/issues/49780) - `@QuarkusMainTest` fails with classloader error with continuous testing
- [#&#8203;49936](https://redirect.github.com/quarkusio/quarkus/pull/49936) - Include suggestions on what to customize when migrating to own FormatMappers
- [#&#8203;50031](https://redirect.github.com/quarkusio/quarkus/pull/50031) - Set up config correctly for isolated `@QuarkusMainTests`
- [#&#8203;50053](https://redirect.github.com/quarkusio/quarkus/pull/50053) - Bump hibernate-orm.version from 7.1.0.Final to 7.1.1.Final
- [#&#8203;50071](https://redirect.github.com/quarkusio/quarkus/issues/50071) - Upgrade Gradle to 9.1 which supports Java 25
- [#&#8203;50075](https://redirect.github.com/quarkusio/quarkus/issues/50075) - Quarkus AWS Lambda API Gateway v2 - Multiple Set-Cookie Headers Not Handled Correctly
- [#&#8203;50076](https://redirect.github.com/quarkusio/quarkus/issues/50076) - Please update to surefire plugin 3.5.4
- [#&#8203;50086](https://redirect.github.com/quarkusio/quarkus/pull/50086) - Update quarkus-fs-util to 1.2.0
- [#&#8203;50092](https://redirect.github.com/quarkusio/quarkus/pull/50092) - Update Maven Surefire & Failsafe plugins to 3.5.4
- [#&#8203;50095](https://redirect.github.com/quarkusio/quarkus/pull/50095) - Bump jakarta.xml.bind:jakarta.xml.bind-api from 4.0.2 to 4.0.4
- [#&#8203;50106](https://redirect.github.com/quarkusio/quarkus/issues/50106) - Quarkus-Flyway is throwing NoSuchMethodException when native compiled with Quarkus >= 3.24
- [#&#8203;50108](https://redirect.github.com/quarkusio/quarkus/pull/50108) - Fix native issue with FlywaySqlException
- [#&#8203;50110](https://redirect.github.com/quarkusio/quarkus/pull/50110) - Bump smallrye-reactive-messaging from 4.28.0 to 4.29.0
- [#&#8203;50111](https://redirect.github.com/quarkusio/quarkus/pull/50111) - Fix deprecated javax Hibernate properties
- [#&#8203;50124](https://redirect.github.com/quarkusio/quarkus/pull/50124) - Redis: improvements
- [#&#8203;50125](https://redirect.github.com/quarkusio/quarkus/pull/50125) - Change the max connections defaults for the Hibernate Search's Elasticsearch client
- [#&#8203;50132](https://redirect.github.com/quarkusio/quarkus/pull/50132) - Bump bouncycastle.version from 1.81 to 1.82
- [#&#8203;50136](https://redirect.github.com/quarkusio/quarkus/pull/50136) - Fix mouse move on active cards
- [#&#8203;50137](https://redirect.github.com/quarkusio/quarkus/pull/50137) - Correctly handle multiple Set-Cookie headers for API Gateway v2
- [#&#8203;50140](https://redirect.github.com/quarkusio/quarkus/issues/50140) - io.vertx.mutiny.sqlclient.Pool.pool(...) doesn't find the (postgres) db driver in native compilation being called from code
- [#&#8203;50141](https://redirect.github.com/quarkusio/quarkus/issues/50141) - NoClassDefFoundError: org/hibernate/community/dialect/CommunityDatabase when no default datasource
- [#&#8203;50143](https://redirect.github.com/quarkusio/quarkus/pull/50143) - Bump Gradle version to 9.1.0
- [#&#8203;50145](https://redirect.github.com/quarkusio/quarkus/issues/50145) - quarkus-messaging-kafka (Kotlin) – Error MetadataExtensions: Provider JvmMetadataExtensions not found in 3.26.4 and lower (works in <= 3.20.2 LTS)
- [#&#8203;50146](https://redirect.github.com/quarkusio/quarkus/pull/50146) - Simplify inference of the SupportedDbKind and avoid NoClassDefFoundError on `CommunityDatabase`
- [#&#8203;50158](https://redirect.github.com/quarkusio/quarkus/pull/50158) - Bump org.postgresql:postgresql from 42.7.7 to 42.7.8
- [#&#8203;50163](https://redirect.github.com/quarkusio/quarkus/issues/50163) - Prevent simultaneous usage of `@InjectMock` and `@InjectSpy` on the same bean during build
- [#&#8203;50165](https://redirect.github.com/quarkusio/quarkus/pull/50165) - Fix improper equals method implementation
- [#&#8203;50167](https://redirect.github.com/quarkusio/quarkus/pull/50167) - Register Reactive SQL Client Drivers
- [#&#8203;50182](https://redirect.github.com/quarkusio/quarkus/pull/50182) - Bump org.assertj:assertj-core from 3.27.4 to 3.27.5 in /devtools/gradle
- [#&#8203;50185](https://redirect.github.com/quarkusio/quarkus/pull/50185) - Bump Elasticsearch version to 9.1.4
- [#&#8203;50189](https://redirect.github.com/quarkusio/quarkus/pull/50189) - Bump org.assertj:assertj-core from 3.27.4 to 3.27.5
- [#&#8203;50191](https://redirect.github.com/quarkusio/quarkus/pull/50191) - Bump jakarta.mail:jakarta.mail-api from 2.1.4 to 2.1.5
- [#&#8203;50194](https://redirect.github.com/quarkusio/quarkus/pull/50194) - Bump io.quarkus:quarkus-platform-bom-maven-plugin from 0.0.123 to 0.0.124
- [#&#8203;50195](https://redirect.github.com/quarkusio/quarkus/pull/50195) - LGTM: Update grafana-dashboard-opentelemetry-logging.json TimeStamp
- [#&#8203;50198](https://redirect.github.com/quarkusio/quarkus/pull/50198) - Prevent simultaneous use of `@InjectMock` and `@InjectSpy`
- [#&#8203;50199](https://redirect.github.com/quarkusio/quarkus/pull/50199) - Fix Kotlin reflection issue in native mode
- [#&#8203;50211](https://redirect.github.com/quarkusio/quarkus/pull/50211) - ArC: fix NPE in InvokerGenerator
- [#&#8203;50213](https://redirect.github.com/quarkusio/quarkus/pull/50213) - Bump org.assertj:assertj-core from 3.27.5 to 3.27.6 in /devtools/gradle
- [#&#8203;50217](https://redirect.github.com/quarkusio/quarkus/pull/50217) - Bump org.bouncycastle:bc-fips from 2.1.1 to 2.1.2
- [#&#8203;50220](https://redirect.github.com/quarkusio/quarkus/pull/50220) - Bump org.assertj:assertj-core from 3.27.5 to 3.27.6
- [#&#8203;50225](https://redirect.github.com/quarkusio/quarkus/issues/50225) - Build fails if a param with a primitive type and type annotation is declared on a method that is called via Invoker
- [#&#8203;50230](https://redirect.github.com/quarkusio/quarkus/pull/50230) - Bump Keycloak version to 26.3.4

### [`v3.28.0`](https://redirect.github.com/quarkusio/quarkus/releases/tag/3.28.0)

[Compare Source](https://redirect.github.com/quarkusio/quarkus/compare/3.27.0...3.28.0)

##### Complete changelog

- [#&#8203;48976](https://redirect.github.com/quarkusio/quarkus/issues/48976) - Hard-coded proxy connect timeout in REST client overrides connect timeout of REST client.
- [#&#8203;49381](https://redirect.github.com/quarkusio/quarkus/issues/49381) - `quarkus.kubernetes-client.devservices.manifests` does not work well with multiple dev services
- [#&#8203;49415](https://redirect.github.com/quarkusio/quarkus/pull/49415) - Still produce KubernetesDevServiceInfoBuildItem when a dev service already exists
- [#&#8203;49808](https://redirect.github.com/quarkusio/quarkus/pull/49808) - Set fixed file/dir permissions for zip entries when building an archive
- [#&#8203;49870](https://redirect.github.com/quarkusio/quarkus/pull/49870) - Bump com.amazonaws:aws-lambda-java-core from 1.3.0 to 1.4.0
- [#&#8203;49903](https://redirect.github.com/quarkusio/quarkus/issues/49903) - MCP Registry for Extensions
- [#&#8203;50001](https://redirect.github.com/quarkusio/quarkus/pull/50001) - Bump version.kotlin from 2.2.10 to 2.2.20
- [#&#8203;50023](https://redirect.github.com/quarkusio/quarkus/pull/50023) - Bump org.eclipse.angus:angus-activation from 2.0.2 to 2.0.3
- [#&#8203;50024](https://redirect.github.com/quarkusio/quarkus/pull/50024) - Bump jakarta.activation:jakarta.activation-api from 2.1.3 to 2.1.4
- [#&#8203;50027](https://redirect.github.com/quarkusio/quarkus/pull/50027) - Dev MCP: Allow enable/disable of methods
- [#&#8203;50036](https://redirect.github.com/quarkusio/quarkus/pull/50036) - Update Maven wrapper to 3.3.4
- [#&#8203;50038](https://redirect.github.com/quarkusio/quarkus/pull/50038) - Jandex: upgrade to 3.5.0
- [#&#8203;50045](https://redirect.github.com/quarkusio/quarkus/pull/50045) - Bump version.kotlin from 2.2.10 to 2.2.20
- [#&#8203;50061](https://redirect.github.com/quarkusio/quarkus/pull/50061) - Add support for the Proxy connect timeout in Quarkus REST Client

### [`v3.27.0`](https://redirect.github.com/quarkusio/quarkus/releases/tag/3.27.0)

[Compare Source](https://redirect.github.com/quarkusio/quarkus/compare/3.26.4...3.27.0)

### [`v3.26.4`](https://redirect.github.com/quarkusio/quarkus/releases/tag/3.26.4)

[Compare Source](https://redirect.github.com/quarkusio/quarkus/compare/3.26.3...3.26.4)

##### Complete changelog

- [#&#8203;49431](https://redirect.github.com/quarkusio/quarkus/issues/49431) - Regression in native build container user handling and new warnings in Quarkus 3.25.0 (Docker-in-Docker CI)
- [#&#8203;49545](https://redirect.github.com/quarkusio/quarkus/pull/49545) - Bump the hibernate group with 5 updates
- [#&#8203;49885](https://redirect.github.com/quarkusio/quarkus/pull/49885) - Fix typos and make minor copyedits in the OIDC auth documentation
- [#&#8203;49901](https://redirect.github.com/quarkusio/quarkus/issues/49901) - Hibernate Reactive does not init database when using multiple named persistence units
- [#&#8203;49916](https://redirect.github.com/quarkusio/quarkus/issues/49916) - LGTM: Otel log output incorrect in Logging Dashboard
- [#&#8203;49917](https://redirect.github.com/quarkusio/quarkus/pull/49917) - OTEL logging dashboard correct timestamp
- [#&#8203;49939](https://redirect.github.com/quarkusio/quarkus/pull/49939) - Manage more Bouncy Castle artifacts to help enforcing dependency convergence throughout Quarkiverse
- [#&#8203;49946](https://redirect.github.com/quarkusio/quarkus/pull/49946) - Update IncludedQuarkusBuildTest to support Gradle 9.1
- [#&#8203;49963](https://redirect.github.com/quarkusio/quarkus/issues/49963) - CLI app created for latest LTS selects unsupported Gradle version, build fails
- [#&#8203;49967](https://redirect.github.com/quarkusio/quarkus/pull/49967) - Remove outdated Renarde references in OIDC and web guides
- [#&#8203;49977](https://redirect.github.com/quarkusio/quarkus/pull/49977) - Trivial: Fix typo in docs
- [#&#8203;49982](https://redirect.github.com/quarkusio/quarkus/pull/49982) - Bump the hibernate group with 5 updates
- [#&#8203;49987](https://redirect.github.com/quarkusio/quarkus/issues/49987) - Bean Validation via JSF broken from 3.24.1+
- [#&#8203;49990](https://redirect.github.com/quarkusio/quarkus/pull/49990) - Account for the null root bean when performing value validation
- [#&#8203;49995](https://redirect.github.com/quarkusio/quarkus/pull/49995) - Log invalid host name in the DevUi CORS filter
- [#&#8203;49999](https://redirect.github.com/quarkusio/quarkus/issues/49999) - Build Cycle error when SmallRye OpenAPI and JFR are used in the same project
- [#&#8203;50000](https://redirect.github.com/quarkusio/quarkus/pull/50000) - Fix Cycle when SmallRye OpenAPI is used with the JFR extension
- [#&#8203;50005](https://redirect.github.com/quarkusio/quarkus/pull/50005) - Bump com.google.code.gson:gson from 2.13.1 to 2.13.2
- [#&#8203;50006](https://redirect.github.com/quarkusio/quarkus/pull/50006) - Small fixes to Dev UI
- [#&#8203;50014](https://redirect.github.com/quarkusio/quarkus/issues/50014) - Agroal - DB connection pool Dev UI empty for MSSQL
- [#&#8203;50016](https://redirect.github.com/quarkusio/quarkus/pull/50016) - Hibernate does not init database when using multiple named persistence units
- [#&#8203;50025](https://redirect.github.com/quarkusio/quarkus/pull/50025) - Bump org.mariadb.jdbc:mariadb-java-client from 3.5.5 to 3.5.6
- [#&#8203;50026](https://redirect.github.com/quarkusio/quarkus/pull/50026) - Fix Build Cycle error when specific extensions and JFR are used in the same project
- [#&#8203;50028](https://redirect.github.com/quarkusio/quarkus/pull/50028) - Copy the Gradle wrapper instead of running the exec goal
- [#&#8203;50029](https://redirect.github.com/quarkusio/quarkus/pull/50029) - Remove outdated note about REST Client logging
- [#&#8203;50030](https://redirect.github.com/quarkusio/quarkus/pull/50030) - Fix for Kafka client config logs reappearing by default
- [#&#8203;50035](https://redirect.github.com/quarkusio/quarkus/pull/50035) - Update an example about REST Client logging
- [#&#8203;50040](https://redirect.github.com/quarkusio/quarkus/issues/50040) - This Gauge has been already registered "http.server.active.connections"
- [#&#8203;50042](https://redirect.github.com/quarkusio/quarkus/pull/50042) - Install appropriate Gradle wrapper in generated projects
- [#&#8203;50043](https://redirect.github.com/quarkusio/quarkus/pull/50043) - Bump smallrye-fault-tolerance.version from 6.9.2 to 6.9.3
- [#&#8203;50050](https://redirect.github.com/quarkusio/quarkus/pull/50050) - Dev UI Agroal: Fix jdbc url parsing for url with ; in it
- [#&#8203;50051](https://redirect.github.com/quarkusio/quarkus/pull/50051) - Hibernate Dev UI: Fix allowed jdbc url with ;
- [#&#8203;50054](https://redirect.github.com/quarkusio/quarkus/pull/50054) - Apply `server.port` tag to all the created Vert.x metrics
- [#&#8203;50062](https://redirect.github.com/quarkusio/quarkus/pull/50062) - Bump org.hibernate.tool:hibernate-tools-language from 7.1.0.Final to 7.1.1.Final in the hibernate group
- [#&#8203;50068](https://redirect.github.com/quarkusio/quarkus/pull/50068) - Bump io.smallrye.common:smallrye-common-bom from 2.13.8 to 2.13.9
- [#&#8203;50074](https://redirect.github.com/quarkusio/quarkus/pull/50074) - Fix hostname when starting Keycloak devServices in shared network
- [#&#8203;50079](https://redirect.github.com/quarkusio/quarkus/pull/50079) - Fix build failure when `quarkus-rest-data-panache` is used

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://redirect.github.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://redirect.github.com/renovatebot/renovate).

### CODE REVIEW

**Comment by goafabric** [comment]
### Branch automerge failure

This PR was configured for branch automerge. However, this is not possible, so it has been raised as a PR instead.
___
 * Branch has one or more failed status checks
